version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      SA_PASSWORD: "#Gfurubu100"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  appWeb:
    image: hikari181/nodejs_idea7:v1
    ports:
      - "3333:80"